#!/bin/bash

# Generate .env.local from AWS SSM Parameters
# This script fetches SSM parameters and creates a .env.local file for local development

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.local"

echo "🔧 Generating .env.local from AWS SSM Parameters..."
echo ""

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI is not installed. Please install it first."
    exit 1
fi

# Check if AWS credentials are configured
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Please run 'aws configure' first."
    exit 1
fi

# Get AWS account ID and region
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=${AWS_REGION:-us-east-1}

echo "📋 Fetching SSM parameters..."
echo "   Account: $AWS_ACCOUNT_ID"
echo "   Region: $AWS_REGION"
echo ""

# Start building .env.local file
cat > "$ENV_FILE" << EOF
# Generated .env.local from AWS SSM Parameters
# Generated on: $(date)
# 
# This file is automatically generated. Do not commit to git.
# To regenerate, run: ./scripts/generate-env-local.sh

# AWS Configuration
AWS_REGION=${AWS_REGION}

# API Port (for local development)
API_PORT=3001

EOF

# Fetch Firebase Service Account from SSM
echo "📥 Fetching Firebase Service Account..."
FIREBASE_PARAM="/onlyvoices/prod/firebase_service_account"

if aws ssm get-parameter --name "$FIREBASE_PARAM" --with-decryption --region "$AWS_REGION" &> /dev/null; then
    FIREBASE_VALUE=$(aws ssm get-parameter --name "$FIREBASE_PARAM" --with-decryption --region "$AWS_REGION" --query 'Parameter.Value' --output text)
    
    # Check if it's already base64 encoded (if it starts with a JSON, we need to encode it)
    if echo "$FIREBASE_VALUE" | jq empty 2>/dev/null; then
        # It's JSON, encode it to base64
        FIREBASE_VALUE=$(echo -n "$FIREBASE_VALUE" | base64 | tr -d '\n')
    fi
    
    echo "FIREBASE_SERVICE_ACCOUNT=$FIREBASE_VALUE" >> "$ENV_FILE"
    echo "   ✅ Firebase Service Account loaded"
else
    echo "   ⚠️  Firebase Service Account not found in SSM: $FIREBASE_PARAM"
    echo "   # FIREBASE_SERVICE_ACCOUNT=your_base64_encoded_service_account_json_here" >> "$ENV_FILE"
fi

echo ""
echo "✅ .env.local generated successfully!"
echo "   Location: $ENV_FILE"
echo ""
echo "⚠️  Note: This file contains sensitive credentials. It's already in .gitignore."
echo "   Do not commit this file to version control."

